In [26]:
import numpy as np
import matplotlib.pylab as plt
from pint import UnitRegistry; AssignQuantity = UnitRegistry().Quantity

In [27]:
D240 = AssignQuantity(0.038e-9,'m^2/s')
D240.ito('micrometer^2/microsecond')
print(D240)

D250 = AssignQuantity(0.075e-9,'m^2/s')
D250.ito('micrometer^2/microsecond')
print(D250)

DNasello260 = AssignQuantity(0.3e-5,'cm^2/s')
DNasello260.ito('micrometer^2/microsecond')
print(DNasello260)

3.8e-05 micrometer ** 2 / microsecond
7.500000000000001e-05 micrometer ** 2 / microsecond
0.00030000000000000003 micrometer ** 2 / microsecond


In [28]:
Price_inverse_Temperatures = np.array([3.4,3.8,4.2])
Price_Temperatures = 1/Price_inverse_Temperatures*1e3
print(Price_Temperatures)
Price_D = np.array([1.8,.7,.2])
print('Inverse Temperatures = ', Price_inverse_Temperatures)
logD = np.log(Price_D); print('log(D) = ', logD)
p = np.polyfit(Price_inverse_Temperatures,logD,1)
print(p)

[294.11764706 263.15789474 238.0952381 ]
Inverse Temperatures =  [3.4 3.8 4.2]
log(D) =  [ 0.58778666 -0.35667494 -1.60943791]
[-2.74653072  9.97737468]


In [45]:
def get_D_of_T(T,AssignQuantity):
    T_inverse_Temperature = 1e3/T; print(T_inverse_Temperature)
    p = [-2.74653072, 9.97737468]
    logD = np.polyval(p,T_inverse_Temperature)
    D = AssignQuantity(np.exp(logD)*1e-5*100,'micrometers^2/microsecond')
    return D

In [48]:
Dvalues = get_D_of_T(Price_Temperatures,AssignQuantity)
print(Dvalues)

[3.4 3.8 4.2]
[ 0.63917023 -0.45944206 -1.55805434]
[0.001894907892855857 0.0006316359647072867 0.00021054532170976294] micrometer ** 2 / microsecond
