In [1]:
import numpy as np

In [23]:
nx = 5
ny = 3
Fliq0 = np.ones([nx,ny])
m,n = np.shape(Fliq0)
print(m)
print(n)

Fliq0[0,:] = 2
# Fliq0[-1,:] = 2
print(Fliq0.T)
print(np.sum(Fliq0))

dy = np.zeros((m,n)) 
D = .1
for i in range(0,m): #go from left column to right
    for j in range(0,n): #go from top row to bottom

            ip1=i+1
            jp1=j+1
            # Boundary Conditions (periodic at ends) #TODO: test this
           
            if i == m-1: #take care of right column condition wrapping to left edge
                ip1 = 0

            if j == n-1: #take care of bottom edge wrapping to top edge
                jp1 = 0

            ux = (Fliq0[ip1,j] - 2*Fliq0[i,j] + Fliq0[i-1,j])
            uy = (Fliq0[i,jp1] - 2*Fliq0[i,j] + Fliq0[i,j-1])

#             dy[i,j] = D*(ux+uy)
            dy[i,j] = D*ux
print(dy.T)
Fliq0 += dy
print(Fliq0.T)
print(np.sum(Fliq0))

5
3
[[2. 1. 1. 1. 1.]
 [2. 1. 1. 1. 1.]
 [2. 1. 1. 1. 1.]]
18.0
[[-0.2  0.1  0.   0.   0.1]
 [-0.2  0.1  0.   0.   0.1]
 [-0.2  0.1  0.   0.   0.1]]
[[1.8 1.1 1.  1.  1.1]
 [1.8 1.1 1.  1.  1.1]
 [1.8 1.1 1.  1.  1.1]]
18.0
